name: Update gist with WakaTime summary
on:
  schedule:
    - cron: '12 10 * * *'
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: wtlllll190812/wakatime-sync@master
        env:
          GH_TOKEN: ${{ vars.GH_TOKEN }}
          GIST_ID: ${{ vars.GIST_ID}}
          WAKATIME_API_KEY: ${{ vars.WAKATIME_API_KEY }}
          SCU_KEY: ${{ vars.SCU_KEY }}
